### ISSUE TITLE
ISERROR missing detection of DIV/0

### ISSUE THREAD

**Issue by misner5** [Row64/Row64_Issue_Tracker#1]
**Row64 Version:**
Row64 1.0

**Operating System & Hardware:**
Windows 10, GPU: RTX 3080, CPU Intel(R) Core(TM) i9-11900K

**Description:**
If you use the IFERROR formula on a division by 0 in Excel it returns an error.  It would helpful if Row64 did the same.

![image](https://user-images.githubusercontent.com/6547193/149676418-d6d873e1-e05a-4516-8c28-fe8b708bc4e2.png)

Here's an example file showing the problem:
[ISERROR_Bug.xlsx](https://github.com/Row64/Row64_Issue_Tracker/files/7877855/ISERROR_Bug.xlsx)

In Cell A1 the formula is =1/0
In Cell A2 the formula is =ISERROR(A1)
It should return TRUE

Thanks for the help...

**Comment by zisner** [comment]
This issue resolved as of Row64 Version 1.01 release.
