### ISSUE TITLE
Unable to import google location history JSON

### ISSUE THREAD

**Issue by KenDodman** [Row64/Row64_Issue_Tracker#3]
**Row64 Version:**
1.01

**Operating System & Hardware:**
windows 11

**Description:**
Try to import google location history via LOADJSON
get Fatal kernel failure, shutting down.

Length of string exceeds 65535

file is almost 1 gig

**Comment by misner5** [comment]
Hello, we've figured out this is a bug / limitation.
You've got some cells here with paragraph text beyond 65535 characters.

For sure our core is well designed and capable of handling this, but we just haven't come across this request yet.

We'll put this in the request queue and update this issue when there's progress.  Our overall goal is to be a leader in data scale & speed so this an important area we want to keep improving in. 

Cheers and thanks for your feedback!
