### ISSUE TITLE
Recipes not displayed

### ISSUE THREAD

**Issue by gonzalezem** [Row64/Row64_Issue_Tracker#6]
**Row64 Version:**

**Operating System & Hardware:**

**Description:**
Please describe the bug in as much detail as possible, with steps to reproduce the problem.
Please paste in screenshots if it helps.

**Comment by gonzalezem** [comment]
Hi,
When I am on dataframe TAB and click the button "Recipes", nothing much happens to the right panel. A grey circle with "Charts" written under it is the only thing that appears. When I click on it, everything disappears.

![row64_issue](https://user-images.githubusercontent.com/15233832/197904567-e25ba3cd-f557-4769-99d6-afaad39c9060.png)

**Comment by zisner** [comment]
Hello @gonzalezem,

It looks like the folder where recipes are stored got partially deleted or didn't fully install. Here is a zip file of the recipes for Row64 V2.0:

https://drive.google.com/file/d/1ykndPAgCZlOJ4IeGETAQZDf1JSAliP7K/view?usp=sharing

You'll want to unzip the file and copy the folder to the following location:

If you're on Windows 10, the recipes should go here: `C:\Users\<USER>\Documents\Row64\_Recipes_V2_0`

If you're on Windows 11, the recipes should go here: `C:\Users\[USER]\OneDrive\Documents\Row64\_Recipes_V2_0`

Hopefully that helps. Please let us know if you have any other problems.

**Comment by gonzalezem** [comment]
Hi, after your comment, I reinstalled it using "Run as administrator" (I forgot this was an option on PCs) and the rwo64 is now fully installed and works well. Thanks!
